# Generated by Django 4.1.5 on 2023-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='Homebg name1')),
                ('name2', models.CharField(max_length=30, verbose_name='Homebg name2')),
                ('name3', models.CharField(max_length=30, verbose_name='Homebg name3')),
                ('name4', models.CharField(max_length=30, verbose_name='Homebg name4')),
            ],
        ),
    ]
