# Generated by Django 4.1.5 on 2023-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homebginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeBG image')),
            ],
        ),
    ]
