# Generated by Django 4.1.5 on 2023-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homebg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name5', models.CharField(max_length=30, verbose_name='Homebest name5')),
                ('name6', models.CharField(max_length=30, verbose_name='Homebest name6')),
                ('img1', models.ImageField(upload_to='media', verbose_name='HomeBest image')),
                ('img2', models.ImageField(upload_to='media', verbose_name='HomeBest image')),
            ],
        ),
    ]
