# Generated by Django 4.1.5 on 2023-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homebest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebest',
            name='name6',
            field=models.CharField(max_length=100, verbose_name='Homebest name6'),
        ),
    ]
