# Generated by Django 4.1.5 on 2023-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homebest_name6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebest',
            name='name6',
            field=models.CharField(max_length=1000, verbose_name='Homebest name6'),
        ),
    ]
