# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeget'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name10', models.CharField(max_length=100, verbose_name='Homeservices name10')),
                ('name11', models.CharField(max_length=1000, verbose_name='Homeservices name11')),
                ('img11', models.ImageField(upload_to='media', verbose_name='Homeservices image')),
                ('price11', models.IntegerField(verbose_name='Homeservices price')),
                ('name12', models.CharField(max_length=1000, verbose_name='Homeservices name12')),
                ('img12', models.ImageField(upload_to='media', verbose_name='Homeservices image')),
                ('price12', models.IntegerField(verbose_name='Homeservices price')),
                ('name13', models.CharField(max_length=1000, verbose_name='Homeservices name13')),
                ('img13', models.ImageField(upload_to='media', verbose_name='Homeservices image')),
                ('price13', models.IntegerField(verbose_name='Homeservices price')),
                ('name14', models.CharField(max_length=1000, verbose_name='Homeservices name14')),
                ('img14', models.ImageField(upload_to='media', verbose_name='Homeservices image')),
                ('price14', models.IntegerField(verbose_name='Homeservices price')),
            ],
        ),
    ]
