# Generated by Django 4.1.5 on 2023-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homehello'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Homeour name')),
                ('name1', models.CharField(max_length=100, verbose_name='Homeour name1')),
                ('name2', models.CharField(max_length=100, verbose_name='Homeour name2')),
                ('name3', models.CharField(max_length=100, verbose_name='Homeour name3')),
                ('name4', models.CharField(max_length=100, verbose_name='Homeour name4')),
                ('name5', models.CharField(max_length=100, verbose_name='Homeour name5')),
                ('name6', models.CharField(max_length=100, verbose_name='Homeour name6')),
            ],
        ),
    ]
